"""Update TravelPlan model for MVP

Revision ID: 59c29dcb6fe1
Revises: c2488db07271
Create Date: 2024-10-30 08:48:47.014818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59c29dcb6fe1'
down_revision = 'c2488db07271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=60), nullable=False))
        batch_op.drop_constraint('travel_plans_ibfk_1', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', mysql.VARCHAR(length=60), nullable=False))
        batch_op.create_foreign_key('travel_plans_ibfk_1', 'locations', ['location_id'], ['id'])
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
